# Generated by Django 5.2.7 on 2025-10-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
