# Generated by Django 5.2.6 on 2025-10-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkflowState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="github", max_length=50)),
                ("owner", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=511, unique=True)),
                ("is_private", models.BooleanField(default=False)),
                ("default_branch", models.CharField(max_length=255)),
                ("topics", models.JSONField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Repositories",
                "indexes": [
                    models.Index(
                        fields=["owner", "name"], name="github_repo_owner_8435ae_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("commit", "Commit"),
                            ("pr", "Pull Request"),
                            ("issue", "Issue"),
                        ],
                        max_length=10,
                    ),
                ),
                ("source_item_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("url", models.URLField(max_length=1024)),
                ("changed_at", models.DateTimeField()),
                ("raw_payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_items",
                        to="github.repository",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["changed_at"], name="github_chan_changed_9284ee_idx"
                    ),
                    models.Index(
                        fields=["item_type", "changed_at"],
                        name="github_chan_item_ty_9ebb7c_idx",
                    ),
                    models.Index(
                        fields=["repository", "changed_at"],
                        name="github_chan_reposit_c007e9_idx",
                    ),
                ],
                "unique_together": {("repository", "item_type", "source_item_id")},
            },
        ),
    ]
