# Generated by Django 5.2.6 on 2025-10-01 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="learning.lesson",
            ),
        ),
    ]
