# Generated by Django 5.2.7 on 2025-10-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_post_change_item"),
        ("learning", "0002_chapter_processed_lesson_processed"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("posts", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("drafted", "Drafted"),
                            ("revised", "Revised"),
                            ("approved", "Approved"),
                            ("error", "Error"),
                        ],
                        default="drafted",
                        max_length=10,
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_batches",
                        to="learning.chapter",
                    ),
                ),
                (
                    "lessons",
                    models.ManyToManyField(
                        related_name="draft_batches", to="learning.lesson"
                    ),
                ),
            ],
        ),
    ]
