# Generated by Django 5.2.7 on 2025-10-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_draftbatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationlog",
            name="token",
            field=models.CharField(
                blank=True,
                help_text="Token for DraftBatch if post is not created yet",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="automationlog",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="content.post",
            ),
        ),
    ]
