name: CI

on:
  push:
    branches:
      - main
      - master
      - work
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pip-audit

      - name: Run CI tasks
        run: |
          chmod +x .ci/task-runner.sh
          .ci/task-runner.sh
